config/routes.rb
Rails.application.routes.draw do

  root 'authentications#welcome'

  post '/signup', to: 'authentications#signup', as: 'signup'
  post '/login', to: 'authentications#login', as: 'login'
  get '/logout', to: 'authentications#logout', as: 'logout'

  get '/files', to: 'containers#index', as: 'files'
  post '/files/upload', to: 'containers#upload', as: 'upload_file'
  delete '/files/delete/:id/', to: 'containers#delete', as: 'delete_file'
  get '/uploads/files/:id/:filename', to: 'containers#download', as: 'download_file', 
    :constraints => { :filename => /[-\w+\.]+/ }

end

app/models/authentication.rb
class Authentication
	include Mongoid::Document
	include Mongoid::Attributes::Dynamic

	before_save :encrypt_password

	field :email, type: String
	field :encrypted_password, type: String
	field :salt, type: String

	has_many :container

	def encrypt_password
		if password.present?
			self.salt = BCrypt::Engine.generate_salt
			self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
		end
		self.password = nil
	end
end

app/models/container.rb
class Container
  include Mongoid::Document

  mount_uploader :file, FileUploader, mount_on: :filename
  belongs_to :authentication, autobuild: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
	before_action :check_authentication, only: [:welcome, :login]

	def welcome

	end

	def login
		@params = login_params
		@auth = Authentication.find_by(email: @params[:email])
		result = :failure
		if !@auth.nil?
			encrypted_password = BCrypt::Engine::hash_secret(@params[:password], @auth.salt)
			if (encrypted_password == @auth.encrypted_password)
				result = :success
			end
		end
		case result
			when :success
				session[:authentication_id] = @auth.id.to_s
				redirect_to files_path
			when :failure
				flash[:failure] = "You aren't logged"
		end
	end

	def logout
		reset_session
		redirect_to root_path
	end

	def signup
		@params = signup_params
		if Authentication.find_by(email: @params[:email]).nil?
			@auth = Authentication.new 	email: @params[:email], 
										password: @params[:password]
			if @auth.save 
				session[:authentication_id] = @auth.id.to_s
				redirect_to files_path
			else
				flash[:failure] = "You aren't signup"
			end
		end
	end

	private
	    def login_params
			params.require(:authentication).permit(:email, :password)
	    end

	    def signup_params
	      params.require(:authentication).permit(:email, :password)
	    end

	    def check_authentication
	    	if session[:authentication_id] != nil
	    		redirect_to files_path
	    	end
	    end
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
	before_action :check_authentication
	

	def index
		@email = Authentication.find(session[:authentication_id]).email
		@containers = Container.where( :authentication_id => session[:authentication_id] )
	end

	def delete
		Container.find(params[:id]).destroy;
		redirect_to files_path
	end

	def upload
		for item in params[:container][:files]
			f = Container.new
			f.file = item
			f.authentication_id = session[:authentication_id]
			f.save!
		end
		redirect_to files_path
	end

	def download
		container = Container.find(params[:id])
		content = container.data.read
		send_data content, type: container.data.file.content_type, disposition: "inline"
		expires_in 0, public: true
	end

	private 
		def check_authentication
			if session[:authentication_id] == nil
				redirect_to root_path
			end
		end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_helper.rb
module FileHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/authentications/login.html.erb
user#login

app/views/authentications/welcome.html.erb
<%= content_tag :div, class: 'welcome-form' do %>
	<ul class="tab-group">
		<li class="tab"><a href="#signup">Sign Up</a></li>
		<li class="tab active"><a href="#login">Log In</a></li>
	</ul>

	<div class="tab-content">
		<div id="login">
			<h1>Welcome Back!</h1>
			<%= form_for(:authentication, url: login_path, method: "post") do |f| %> 
				<div class="field-wrap">
					<%= f.label :email do %>
						Email Address<span class="req">*</span>
					<% end %>
					<%= f.text_field :email, :autocomplete => :on, :required => :true %>
				</div>

				<div class="field-wrap">
					<%= f.label :password do %>
						Password<span class="req">*</span>
					<% end %>
					<%= f.password_field :password, :autocomplete => :off, :required => :true %>
				</div>
				<button type="submit" class="button button-block"/>Log In</button>
			<% end %>
		</div>

		<div id="signup"> 
			<h1>Sign Up</h1>
			<%= form_for(:authentication, url: signup_path, method: "post") do |f| %> 
				<div class="field-wrap">
					<%= f.label :email do %>
						Email Address<span class="req">*</span>
					<% end %>
					<%= f.text_field :email, :autocomplete => :on, :required => :true %>
				</div>
				
				<div class="field-wrap">
					<%= f.label :password do %>
						Password<span class="req">*</span>
					<% end %>
					<%= f.password_field :password, :autocomplete => :off, :required => :true %>
				</div>

				<div class="field-wrap">
					<%= f.label :password_confirm do %>
						Confirm Password<span class="req">*</span>
					<% end %>
					<%= f.password_field :password_confirm, :autocomplete => :off, :required => :true %>
				</div>
				<button type="submit" class="button button-block"/>Get Started</button>
			<% end %>
		</div>
	</div>
<% end %>

app/views/containers/delete.html.erb
file#destroy.html.erb

app/views/containers/index.html.erb
<nav>
	<div class="email"><%= @email %></div><span>,</span>
	<div class="logout"><%= link_to 'Log out', logout_path %></div>
</nav>

<div class="containers-wrapper">
<% unless @containers.nil? || @containers.length == 0 %>
	<table>
		<thead>
			<tr>
				<th>ID</th>
				<th>Name</th>
				<th>Size</th>
				<th>URL</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @containers.each do |container| %>
				<tr>
					<td><%= container.id %></td>
					<td><%= container.filename %></td>
					<td><%= container.file.size %></td>
					<td><%= link_to 'Link', root_url + container.file.url %></td>
					<td><%= link_to 'Destroy', delete_file_path(container.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

<%if false%>
<input type="file" name="file-1[]" id="file-1" class="inputfile inputfile-1" data-multiple-caption="{count} files selected" multiple />
	
<%end%>
	<div class="upload-form-wrapper">

		<%= form_tag(upload_file_path, method: :post, multipart: true) do %>
			<%= file_field(:container,
											:files,
											:multiple => true,
											"data-multiple-caption" => "{count} Files selected",
											:class => "inputfile inputfile-1") %>
			<%= label(:container, :files) do %>
				<svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg> <span>Choose a file&hellip;</span>
			<% end %>

			<%= submit_tag("Upload", id: :submit_ , class: :inputfile) %>
			<%= label(:submit, nil) do %>
				<span>Upload</span>
			<% end %>
		<% end %>
	</div>
</div>

app/views/containers/upload.html.erb
file#create.html.erb

<pre><%= @info %></pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FilesTest</title>
  <%= stylesheet_link_tag 'css/application', media: 'all','data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

<%= yield %>

<%= javascript_include_tag 'https://code.jquery.com/jquery-2.2.0.min.js' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>